name: WhiteStone
options:
  bundleIdPrefix: com.whitestone
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
targets:
  WhiteStone:
    type: application
    platform: iOS
    sources:
      - WhiteStone
    settings:
      base:
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait
        SWIFT_EMIT_LOC_STRINGS: YES
        GENERATE_INFOPLIST_FILE: YES
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
        PRODUCT_BUNDLE_IDENTIFIER: com.whitestone.WhiteStone
        INFOPLIST_KEY_CFBundleDisplayName: White Stone
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        DEVELOPMENT_ASSET_PATHS: "\"WhiteStone/Preview Content\""
